export const OFFICE_LIST_REQUEST = "OFFICE_LIST_REQUEST";
export const OFFICE_LIST_SUCCESS = "OFFICE_LIST_SUCCESS";
export const OFFICE_LIST_FAILURE = "OFFICE_LIST_FAILURE";

export const OFFICE_REQUEST = "OFFICE_REQUEST";
export const OFFICE_SUCCESS = "OFFICE_SUCCESS";
export const OFFICE_FAILURE = "OFFICE_FAILURE";


export const OFFICE_UPDATE_REQUEST = "OFFICE_UPDATE_REQUEST";
export const OFFICE_UPDATE_SUCCESS = "OFFICE_UPDATE_SUCCESS";
export const OFFICE_UPDATE_FAILURE = "OFFICE_UPDATE_FAILURE";
