export const STAFF_LIST_REQUEST = "STAFF_LIST_REQUEST";
export const STAFF_LIST_SUCCESS = "STAFF_LIST_SUCCESS";
export const STAFF_LIST_FAILURE = "STAFF_LIST_FAILURE";

export const TEACHERS_LIST_REQUEST = "TEACHERS_LIST_REQUEST";
export const TEACHERS_LIST_SUCCESS = "TEACHERS_LIST_SUCCESS";
export const TEACHERS_LIST_FAILURE = "TEACHERS_LIST_FAILURE";
