export const STUDENTS_LIST_REQUEST = "STUDENTS_LIST_REQUEST";
export const STUDENTS_LIST_SUCCESS = "STUDENTS_LIST_SUCCESS";
export const STUDENTS_LIST_FAILURE = "STUDENTS_LIST_FAILURE";

export const STUDENT_PROFILE_REQUEST = "STUDENT_PROFILE_REQUEST";
export const STUDENT_PROFILE_SUCCESS = "STUDENT_PROFILE_SUCCESS";
export const STUDENT_PROFILE_FAILURE = "STUDENT_PROFILE_FAILURE";

export const STUDENT_PROFILE_UPDATE_REQUEST = "STUDENT_PROFILE_UPDATE_REQUEST";
export const STUDENT_PROFILE_UPDATE_SUCCESS = "STUDENT_PROFILE_UPDATE_SUCCESS";
export const STUDENT_PROFILE_UPDATE_FAILURE = "STUDENT_PROFILE_UPDATE_FAILURE";

export const STUDENT_PROFILE_DELETE_REQUEST = "STUDENT_PROFILE_DELETE_REQUEST";
export const STUDENT_PROFILE_DELETE_SUCCESS = "STUDENT_PROFILE_DELETE_SUCCESS";
export const STUDENT_PROFILE_DELETE_FAILURE = "STUDENT_PROFILE_DELETE_FAILURE";
export const STUDENT_PROFILE_DELETE_RESET = "STUDENT_PROFILE_DELETE_RESET";
